Nix executor [PLEN-200 follow up]
digital-asset/daml-helm-charts pull request #14
Opened 2023-03-22 10:30 UTC by adamma-da

2023-03-22 16:47 UTC, lucb-da approved these changes

2023-03-22 17:07 UTC, lucb-da requested changes
Not sure if the nix config is as minimal as it can be.

2023-03-22 17:07 UTC, lucb-da commented on shell.nix
I don't think a `shell.nix` is required.
It is only useful if we expect users to start a `nix-shell` to work on the repository.

2023-03-23 09:57 UTC, adamma-da commented
@lucb-da Changes proposed by you have been implemented :)

2023-03-23 11:19 UTC, lucb-da commented on .circleci/config.yml
>        - build-cr
Is the `build-cr` step still need, or even working ?
It installs the dependencies, but it should not be required anymore if they are provided by nix.
And I am not sure `apk` is available in the nix environment.

2023-03-23 14:38 UTC, closed without merging